version: "3"
services: 
  vrising:
    container_name: vrising-server
    image: solareon/vrising-svr:latest
    volumes: 
      - ~/vrising/server:/vrising/server
      - ~/vrising/data:/vrising/data
    environment:
      - SERVER_NAME="A V-Rising Server"
      - SERVER_DESCRIPTION="A server for my friends"
      - GAME_PORT=27015
      - QUERY_PORT=27016
      - MAX_USERS=40
      - MAX_ADMIN=4
      - SAVE_NAME="world1"
      - SERVER_PASS="password"
      - STEAM_LIST=true
      - AUTOSAVE_NUM=50
      - AUTOSAVE_INT=300
      - GAME_PRESET="StandardPvP"
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped